testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51MWyP4CuvF2D138rU4yGyxubKOgBEz3VkGGqnQm8Z0ChVPzwU2nJMMpNSb3KDStUn3ntf8E0Jxssblpf7FMqnylz00xUkMsqu0" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_dR6cMR32GcHGfeM4gl" #only needed if using Stripe
client_id = "246297739053-p905v6314hedbhljq141kon9svcgb1fl.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = '"https://donatecho2.streamlit.app'
redirect_url = "https://donatecho2.streamlit.app"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
